### PR TITLE
Add public key for the signed drivers

### PR DESCRIPTION
**Pull request by mregmi**
This key is needed for Secure boot enabled system. The user needs to enroll them to their MOK list.
Signed-off-by: Manish Regmi <manish.regmi@intel.com>

### CODE REVIEW

**Comment by uMartinXu** [comment]
Can we change commit log to:

release: add the public key for the signed drivers
The public key can be used by users to enable the secure boot.
For the technical detail about the secure boot and driver signing,
please see
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_monitoring_and_updating_the_kernel/signing-a-kernel-and-modules-for-secure-boot_managing-monitoring-and-updating-the-kernel

Signed-off-by: Manish Regmi <manish.regmi@intel.com>

**Comment by uMartinXu** [comment]
This PR looks good to me. @chaitanya1731 @hershpa  please also have a look at it. Thanks!

**Comment by chaitanya1731** [comment]
looks good to me.

**Comment by hershpa** [comment]
This PR looks good.

**Pull request merged**
