### PR TITLE
Create hadolint.yml

### PR DESCRIPTION
**Pull request by hershpa**
GH Action workflow to run Hadolint on Dockerfile.
Signed-off-by: Hersh Pathak hersh.pathak@intel.com

### CODE REVIEW

**Comment by uMartinXu** [comment]
@chaitanya1731 @mregmi could you please also help review this PR?

**Comment by chaitanya1731** [comment]
I like the functionality. Will this action run on every push/pr on every branch? can we just set it to run on main branch?

**Comment by mregmi** [comment]
is there a test/sample result it produces. does the current codebase pass without error?

**Comment by hershpa** [comment]
> I like the functionality. Will this action run on every push/pr on every branch? can we just set it to run on main branch?

Thanks, updated to run on every push/pr to main branch.

**Comment by hershpa** [comment]
failure-threshold is set to error. Other options are  [|warning | info | style | ignore]. For more details, refer here: https://github.com/hadolint/hadolint-action

**Comment by hershpa** [comment]
> is there a test/sample result it produces. does the current codebase pass without error?

https://github.com/hershpa/intel-data-center-gpu-driver-for-openshift-1/actions/runs/4855900845

**Comment by hershpa** [comment]
The results above show that hadolint is enforcing some best practices (nice to have) but they do not impact functionality. It may be better to set failure-threshold to warning. Let's keep this PR on hold for now as a lower priority.

**Comment by hershpa** [comment]
@chaitanya1731, do we need this PR or we can close it?

**Comment by chaitanya1731** [comment]
I think we can merge this to check for any linting errors. @uMartinXu what do you think.

**Pull request closed without merging**
