### PR TITLE
docker: Update README.md

### PR DESCRIPTION
**Pull request by hershpa**
Fix minor typo and update example to refer to Intel GPU driver version 555 release tags.
Signed-off-by: Hersh Pathak <hersh.pathak@intel.com>

### CODE REVIEW

**Comment by hershpa** [comment]
Hi @chaitanya1731 and @uMartinXu, can you please help review this PR?

**Comment by chaitanya1731** [comment]
Looks good to me

**Comment by hershpa** [comment]
Small update, pls review and provide feedback

**Comment by uMartinXu** [comment]
The patch looks good to me.

**Pull request merged**
