### PR TITLE
docker: Set initial DRIVER_VERSION to 1.0.0

### PR DESCRIPTION
**Pull request by hershpa**
Signed-off-by: Hersh Pathak <hersh.pathak@intel.com>

### CODE REVIEW

**Comment by hershpa** [comment]
@chaitanya1731 and @uMartinXu, pls review.

**Comment by hershpa** [comment]
Is this PR ready to go?

**Comment by chaitanya1731** [comment]
Looks Good.

**Comment by uMartinXu** [comment]
Looks Good to me. :-)

**Pull request merged**
