### PR TITLE
docker: Improve driver container image size

### PR DESCRIPTION
**Pull request by hershpa**
Copy only the necessary ko files and firmware binaries to minimize final driver container image size.
See [#33](https://github.com/intel/intel-data-center-gpu-driver-for-openshift/issues/33) for more details.
Signed-off-by: Hersh Pathak hersh.pathak@intel.com

### CODE REVIEW

**Comment by chaitanya1731** [comment]
I suggest to please let previous PR be merged and then rebase and make the new changes.. I see most of the changes are similar to previous PR #41 .

**Comment by hershpa** [comment]
New driver container compressed image size is down from 256 MiB to 180.1 MiB. Reduced by 75.9 MiB. [build log](https://github.com/intel/intel-data-center-gpu-driver-for-openshift/files/11502935/intel-dgpu-on-premise-build-mode-q27p4-undefined.log)

**Comment by hershpa** [comment]
> I suggest to please let previous PR be merged and then rebase and make the new changes.. I see most of the changes are similar to previous PR #41 .

Yes, no problem. That is the plan.

**Comment by hershpa** [comment]
@uMartinXu, @vbedida79, @chaitanya1731, please help review this PR.

**Comment by hershpa** [comment]
Note: modules.order or modules.builtin are copied as they are needed (if not, a warning generated by depmod command is observed in the build log). For more details on the purpose of those files, visit https://www.kernel.org/doc/Documentation/kbuild/kbuild.txt.

**Comment by vbedida79** [comment]
@hershpa @chaitanya1731 Just noticed, the builder image has current dir `/build`  with `WORKDIR` declared. I suggest we remove, `/build/` in any of the subsequent commands. This would be for building i915, modules dir and firmware parts. Shouldn't affect functionality of image. More related to readability. Thoughts?

**Comment by hershpa** [comment]
> @hershpa @chaitanya1731 Just noticed, the builder image has current dir `/build` with `WORKDIR` declared. I suggest we remove, `/build/` in any of the subsequent commands. This would be for building i915, modules dir and firmware parts. Shouldn't affect functionality of image. More related to readability. Thoughts?

Good point. I would still prefer being explicit with the path for ease and readability.

**Comment by hershpa** [comment]
closing this PR, refer to PR https://github.com/intel/intel-data-center-gpu-driver-for-openshift/pull/43

**Pull request closed without merging**
